### ISSUE TITLE
足し算

### ISSUE THREAD

**Issue by takumi-333** [takeyamayuki/git-traning-2023-06-16#2]
## 操作手順
* 足し算を行なったら
* 結果が引き算されたものになった

## 本来の想定
* 足し算を行なったら
* 結果が足し算されたものになってほしい

## 操作環境
* MAC
* 新しめ
* Chrome
* 114.....

**Comment by takeyamayuki** [comment]
https://github.com/takeyamayuki/git-traning-2023-06-16/issues/3 と同じissueなので閉じます
